pins:
  - pin: 13
    function: Ignition Switch KL15 / Battery Voltage Analog Input
    class: analog_inputs
    ts_name: 13 - IN_VIGN
    color: red


info:
  title: S105
  name: S105
  image:
    file: 121pin.jpg
  pins:
    - pin: 1a
      x: 286
      y: 582

    - pin: 2a
      x: 456
      y: 582

    - pin: 3a
      x: 375
      y: 405

    - pin: 4a
      x: 286
      y: 250

    - pin: 5a
      x: 456
      y: 250

    # 6-24 segment
    - pin: 6a
      x: 2193
      y: 250

    - pin: 7a
      x: 2113
      y: 250

    - pin: 8a
      x: 2033
      y: 250

    - pin: 9a
      x: 1953
      y: 250

    - pin: 10a
      x: 1873
      y: 250

    - pin: 11a
      x: 1793
      y: 250

    - pin: 12a
      x: 1713
      y: 250

    - pin: 13a
      x: 1633
      y: 250

    - pin: 14a
      x: 1553
      y: 250

    - pin: 15a
      x: 1473
      y: 250

    - pin: 16a
      x: 1393
      y: 250

    - pin: 17a
      x: 1313
      y: 250

    - pin: 18a
      x: 1233
      y: 250

    - pin: 19a
      x: 1153
      y: 250

    - pin: 20a
      x: 1073
      y: 250

    - pin: 21a
      x: 993
      y: 250

    - pin: 22a
      x: 913
      y: 250

    - pin: 23a
      x: 833
      y: 250

    - pin: 24a
      x: 753
      y: 250

    # 25-43 segment
    - pin: 25a
      x: 2193
      y: 330

    - pin: 26a
      x: 2113
      y: 330

    - pin: 27a
      x: 2033
      y: 330

    - pin: 28a
      x: 1953
      y: 330

    - pin: 29a
      x: 1873
      y: 330

    - pin: 30a
      x: 1793
      y: 330

    - pin: 31a
      x: 1713
      y: 330

    - pin: 32a
      x: 1633
      y: 330

    - pin: 33a
      x: 1553
      y: 330

    - pin: 34a
      x: 1473
      y: 330

    - pin: 35a
      x: 1393
      y: 330

    - pin: 36a
      x: 1313
      y: 330

    - pin: 37a
      x: 1233
      y: 330

    - pin: 38a
      x: 1153
      y: 330

    - pin: 39a
      x: 1073
      y: 330

    - pin: 40a
      x: 993
      y: 330

    - pin: 41a
      x: 913
      y: 330

    - pin: 42a
      x: 833
      y: 330

    - pin: 43a
      x: 753
      y: 330

    # 44-62 segment
    - pin: 44a
      x: 2193
      y: 495

    - pin: 45a
      x: 2113
      y: 495

    - pin: 46a
      x: 2033
      y: 495

    - pin: 47a
      x: 1953
      y: 495

    - pin: 48a
      x: 1873
      y: 495

    - pin: 49a
      x: 1793
      y: 495

    - pin: 50a
      x: 1713
      y: 495

    - pin: 51a
      x: 1633
      y: 495

    - pin: 52a
      x: 1553
      y: 495

    - pin: 53a
      x: 1473
      y: 495

    - pin: 54a
      x: 1393
      y: 495

    - pin: 55a
      x: 1313
      y: 495

    - pin: 56a
      x: 1233
      y: 495

    - pin: 57a
      x: 1153
      y: 495

    - pin: 58a
      x: 1073
      y: 495

    - pin: 59a
      x: 993
      y: 495

    - pin: 60a
      x: 913
      y: 495

    - pin: 61a
      x: 833
      y: 495

    - pin: 62a
      x: 732
      y: 495

    # 63-81 segment
    - pin: 63a
      x: 2193
      y: 579

    - pin: 64a
      x: 2113
      y: 579

    - pin: 65a
      x: 2033
      y: 579

    - pin: 66a
      x: 1953
      y: 579

    - pin: 67a
      x: 1873
      y: 579

    - pin: 68a
      x: 1793
      y: 579

    - pin: 69a
      x: 1713
      y: 579

    - pin: 70a
      x: 1633
      y: 579

    - pin: 71a
      x: 1553
      y: 579

    - pin: 72a
      x: 1473
      y: 579

    - pin: 73a
      x: 1393
      y: 579

    - pin: 74a
      x: 1313
      y: 579

    - pin: 75a
      x: 1233
      y: 579

    - pin: 76a
      x: 1153
      y: 579

    - pin: 77a
      x: 1073
      y: 579

    - pin: 78a
      x: 993
      y: 579

    - pin: 79a
      x: 913
      y: 579

    - pin: 80a
      x: 833
      y: 579

    - pin: 81a
      x: 732
      y: 579

