pins:
  # Low side outputs
  - pin: 1
    id: D12
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 1
    
  - pin: 2
    id: D13
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 2

  - pin: 3
    id: D14
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 3
    
  - pin: 4
    id: D15
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 4
    
  - pin: 5
    id: C6
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 5
    
  - pin: 6
    id: C7
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 6
    
  - pin: 7
    id: C9
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 7
    
  - pin: 8
    id: A8
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 8

    # Low side

  - pin: 9
    id: D10
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Boost controler

  - pin: 10
    id: B13
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Idle valve 1

  - pin: 11
    id: B12
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Tacho output

  - pin: 12
    id: D8
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Low side output 1

  - pin: 13
    id: B14
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Low side output 2

  - pin: 14
    id: B15
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Low side output 3


  - pin: 15
    id: D9
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Fan output

  - pin: 16
    id: D11
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Fuel pump output

  - pin: 17
    id: E7
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: DBW_PWM

  - pin: 18
    id: B0
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: DBW_DIS

  - pin: 19
    id: B1
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: DBW_DIR
    
  # High side
  
  - pin: 20
    id: E15
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 1
    
  - pin: 21
    id: E14
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 2
    
  - pin: 22
    id: E13
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 3
    
  - pin: 23
    id: E12
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 4
    
  - pin: 24
    id: E11
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 5
    
  - pin: 25
    id: E10
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 6
    
  - pin: 26
    id: E9
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 7
    
  - pin: 27
    id: E8
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 8
    
  # SENSORS
  
  - pin: 28
    id: EFI_ADC_14
    class: analog_inputs
    function: Sensor Input
    ts_name: Battery reference voltage

  - pin: 29
    id: EFI_ADC_0
    class: analog_inputs
    function: Sensor Input
    ts_name: Spare analog input 1

  - pin: 30
    id: EFI_ADC_1
    class: analog_inputs
    function: Sensor Input
    ts_name: Spare analog input 2

  - pin: 31
    id: EFI_ADC_10
    class: analog_inputs
    function: Sensor Input
    ts_name: Clt sensor

  - pin: 32
    id: EFI_ADC_11
    class: analog_inputs
    function: Sensor Input
    ts_name: Iat sensor

  - pin: 33
    id: EFI_ADC_12
    class: analog_inputs
    function: Sensor Input
    ts_name: Oilpress sensor

  - pin: 34
    id: EFI_ADC_13
    class: analog_inputs
    function: Sensor Input
    ts_name: Fuelpress sensor

  - pin: 35
    id: EFI_ADC_4
    class: analog_inputs
    function: Sensor Input
    ts_name: Spare analog input 3

  - pin: 36
    id: EFI_ADC_5
    class: analog_inputs
    function: Sensor Input
    ts_name: MAP sensor

  - pin: 37
    id: EFI_ADC_6
    class: analog_inputs
    function: Sensor Input
    ts_name: Build-in wideband sensor

  - pin: 38
    id: EFI_ADC_7
    class: analog_inputs
    function: Sensor Input
    ts_name: Baro sensor

  - pin: 39
    id: [A14, A14]
    class: [event_inputs, switch_inputs]
    function: Camshaft Sensor (VR+/Hall)
    type: hall
    ts_name: Camshaft Sensor

  - pin: 40
    id: [A15, A15]
    class: [event_inputs, switch_inputs]
    function: Crankshaft Sensor (VR+/Hall)
    type: hall
    ts_name: Crankshaft Sensor

  - pin: 41
    id: [D4, D4]
    class: [event_inputs, switch_inputs]
    function: VSS (VR+/Hall)
    type: hall
    ts_name: VSS
  
  - pin: 42
    id: [D3, D3]
    class: [event_inputs, switch_inputs]
    function: Spare trigger input (VR+/Hall)
    type: hall
    ts_name: Spare trigger input

  - pin: 43
    id: EFI_ADC_15
    class: analog_inputs
    function: Sensor Input
    ts_name: TPS sensor

  - pin: 44
    id: B9
    class: switch_inputs
    function: Digital Input
    type: hall
    ts_name: Digital Input 1

  - pin: 45
    id: E0
    class: switch_inputs
    function: Digital Input
    type: hall
    ts_name: Digital Input 2

  - pin: 46
    id: D5
    class: switch_inputs
    function: Digital Input
    type: hall
    ts_name: Digital Input 3

  - pin: 47
    id: D6
    class: switch_inputs
    function: Digital Input
    type: hall
    ts_name: Digital Input 4



    
 

